export const dhakaAreas = [
	"Adabor",
	"Airport",
	"Ashkona",
	"Aftabnagar",
	"Banani",
	"Banasree",
	"Bangshal",
	"Baridhara",
	"Baridhara DOHS",
	"Basabo",
	"Badda",
	"Bashundhara R/A",
	"Chawkbazar",
	"Dakshinkhan",
	"Dhanmondi",
	"Dilkusha",
	"East Rampura",
	"Fakirapool",
	"Farmgate",
	"Gendaria",
	"Gulshan 1",
	"Gulshan 2",
	"Hatirjheel",
	"Islampur",
	"Jigatola",
	"Joar Sahara",
	"Kakrail",
	"Kalabagan",
	"Kallyanpur",
	"Karwan Bazar",
	"Kazipara",
	"Khilgaon",
	"Khilkhet",
	"Lalbagh",
	"Lalmatia",
	"Malibagh",
	"Merul Badda",
	"Middle Badda",
	"Mirpur 1",
	"Mirpur 2",
	"Mirpur 6",
	"Mirpur 10",
	"Mirpur 11",
	"Mirpur 12",
	"Mirpur 13",
	"Mirpur 14",
	"Mohakhali",
	"Mohammadpur",
	"Moghbazar",
	"Nakhalpara",
	"Natun Bazar",
	"Niketan",
	"Nikunja",
	"Old Dhaka",
	"Pallabi",
	"Paltan",
	"Purana Paltan",
	"Rupnagar",
	"Sadarghat",
	"Segunbagicha",
	"Shahjadpur",
	"Shankar",
	"Shantinagar",
	"Shewrapara",
	"Shyamoli",
	"Sutrapur",
	"Taltola",
	"Tejgaon",
	"Tejgaon Industrial Area",
	"Tolarbag",
	"Uttar Badda",
	"Uttara",
	"Uttara Sector 3",
	"Uttara Sector 4",
	"Uttara Sector 7",
	"Uttara Sector 9",
	"Uttara Sector 10",
	"Uttara Sector 11",
	"Uttara Sector 12",
	"Uttara Sector 13",
	"Uttara Sector 14",
	"Vatara",
	"Wari",
] as const;
