// export const serviceCategories = [
// 	{
// 		name: "Cleaning",
// 		imageUrl: "/images/categories/cleaning.jpg",
// 		services: [
// 			"House Cleaning",
// 			"Deep Cleaning",
// 			"Kitchen Cleaning",
// 			"Bathroom Cleaning",
// 			"Sofa Cleaning",
// 			"Carpet Cleaning",
// 		],
// 	},
// 	{
// 		name: "Plumbing",
// 		imageUrl: "/images/categories/plumbing.jpg",
// 		services: [
// 			"Pipe Repair",
// 			"Faucet Repair",
// 			"Water Tank Repair",
// 			"Drain Cleaning",
// 			"Toilet Repair",
// 			"Leak Repair",
// 		],
// 	},
// 	{
// 		name: "Electrical",
// 		imageUrl: "/images/categories/electrical.jpg",
// 		services: [
// 			"Electrical Repair",
// 			"Switch & Socket Repair",
// 			"Fan Installation",
// 			"Light Installation",
// 			"Wiring",
// 			"Circuit Breaker Repair",
// 		],
// 	},
// 	{
// 		name: "AC & Cooling",
// 		imageUrl: "/images/categories/ac-cooling.jpg",
// 		services: [
// 			"AC Servicing",
// 			"AC Repair",
// 			"AC Installation",
// 			"AC Gas Refill",
// 			"AC Cleaning",
// 		],
// 	},
// 	{
// 		name: "Appliance Repair",
// 		imageUrl: "/images/categories/appliance-repair.jpg",
// 		services: [
// 			"Refrigerator Repair",
// 			"Washing Machine Repair",
// 			"Microwave Repair",
// 			"Oven Repair",
// 			"TV Repair",
// 		],
// 	},
// 	{
// 		name: "Painting",
// 		imageUrl: "/images/categories/painting.jpg",
// 		services: [
// 			"Interior Painting",
// 			"Exterior Painting",
// 			"Wall Painting",
// 			"Ceiling Painting",
// 			"Touch-up Painting",
// 		],
// 	},
// 	{
// 		name: "Carpentry",
// 		imageUrl: "/images/categories/carpentry.jpg",
// 		services: [
// 			"Furniture Repair",
// 			"Door Repair",
// 			"Cabinet Repair",
// 			"Furniture Assembly",
// 			"Custom Furniture",
// 		],
// 	},
// 	{
// 		name: "Moving",
// 		imageUrl: "/images/categories/moving.jpg",
// 		services: [
// 			"Home Moving",
// 			"Office Moving",
// 			"Furniture Moving",
// 			"Packing & Unpacking",
// 			"Loading & Unloading",
// 		],
// 	},
// 	{
// 		name: "Pest Control",
// 		imageUrl: "/images/categories/pest-control.jpg",
// 		services: [
// 			"Cockroach Control",
// 			"Mosquito Control",
// 			"Ant Control",
// 			"Termite Control",
// 			"Bed Bug Control",
// 		],
// 	},
// 	{
// 		name: "Home Security",
// 		imageUrl: "/images/categories/home-security.jpg",
// 		services: [
// 			"CCTV Installation",
// 			"CCTV Repair",
// 			"Smart Lock Installation",
// 			"Door Lock Repair",
// 			"Security System Setup",
// 		],
// 	},
// 	{
// 		name: "Gardening",
// 		imageUrl: "/images/categories/gardening.jpg",
// 		services: [
// 			"Garden Maintenance",
// 			"Plant Care",
// 			"Lawn Care",
// 			"Tree Trimming",
// 			"Plant Installation",
// 		],
// 	},
// 	{
// 		name: "Handyman",
// 		imageUrl: "/images/categories/handyman.jpg",
// 		services: [
// 			"Furniture Assembly",
// 			"Wall Mounting",
// 			"Curtain Installation",
// 			"Shelf Installation",
// 			"Minor Repairs",
// 		],
// 	},
// 	{
// 		name: "Glass & Aluminum",
// 		imageUrl: "/images/categories/glass-aluminum.jpg",
// 		services: [
// 			"Glass Repair",
// 			"Glass Installation",
// 			"Window Repair",
// 			"Aluminum Work",
// 			"Sliding Door Repair",
// 		],
// 	},
// 	{
// 		name: "Roof & Waterproofing",
// 		imageUrl: "/images/categories/roof-waterproofing.jpg",
// 		services: [
// 			"Roof Repair",
// 			"Waterproofing",
// 			"Leak Repair",
// 			"Roof Cleaning",
// 			"Damp Treatment",
// 		],
// 	},
// 	{
// 		name: "Laundry",
// 		imageUrl: "/images/categories/laundry.jpg",
// 		services: [
// 			"Wash & Fold",
// 			"Ironing",
// 			"Dry Cleaning",
// 			"Laundry Pickup",
// 			"Laundry Delivery",
// 		],
// 	},
// 	{
// 		name: "Interior & Decor",
// 		imageUrl: "/images/categories/interior-decor.jpg",
// 		services: [
// 			"Interior Design",
// 			"Wall Decor",
// 			"Curtain Installation",
// 			"Lighting Design",
// 			"Home Decoration",
// 		],
// 	},
// 	{
// 		name: "Bathroom Services",
// 		imageUrl: "/images/categories/bathroom-services.jpg",
// 		services: [
// 			"Bathroom Repair",
// 			"Tile Repair",
// 			"Grouting",
// 			"Shower Installation",
// 			"Bathroom Renovation",
// 		],
// 	},
// 	{
// 		name: "Kitchen Services",
// 		imageUrl: "/images/categories/kitchen-services.jpg",
// 		services: [
// 			"Kitchen Repair",
// 			"Kitchen Cabinet Repair",
// 			"Sink Installation",
// 			"Kitchen Renovation",
// 			"Countertop Installation",
// 		],
// 	},
// ] as const;
